// Code generated by protoc-gen-goshim. DO NOT EDIT.

package v1

import slim "go.opentelemetry.io/proto/slim/otlp/trace/v1"

type (
	TracesData    = slim.TracesData
	ResourceSpans = slim.ResourceSpans
	ScopeSpans    = slim.ScopeSpans
	Span          = slim.Span
	Status        = slim.Status
	SpanFlags     = slim.SpanFlags
)
