// Code generated by protoc-gen-goshim. DO NOT EDIT.

package v1

import slim "go.opentelemetry.io/proto/slim/otlp/common/v1"

type (
	AnyValue             = slim.AnyValue
	ArrayValue           = slim.ArrayValue
	KeyValueList         = slim.KeyValueList
	KeyValue             = slim.KeyValue
	InstrumentationScope = slim.InstrumentationScope
)
