version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  - package-ecosystem: gomod
    directory: /
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
  - package-ecosystem: gomod
    directory: /otlp
    labels:
      - dependencies
      - go
      - "Skip Changelog"
    schedule:
      day: sunday
      interval: weekly
