// Code generated by protoc-gen-goshim. DO NOT EDIT.

package v1development

import slim "go.opentelemetry.io/proto/slim/otlp/profiles/v1development"

type (
	ProfilesData           = slim.ProfilesData
	ResourceProfiles       = slim.ResourceProfiles
	ScopeProfiles          = slim.ScopeProfiles
	Profile                = slim.Profile
	AttributeUnit          = slim.AttributeUnit
	Link                   = slim.Link
	ValueType              = slim.ValueType
	Sample                 = slim.Sample
	Mapping                = slim.Mapping
	Location               = slim.Location
	Line                   = slim.Line
	Function               = slim.Function
	AggregationTemporality = slim.AggregationTemporality
)
