// Copyright 2023, OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: opentelemetry/proto/collector/profiles/v1development/profiles_service.proto

package v1development

import (
	v1development "go.opentelemetry.io/proto/slim/otlp/profiles/v1development"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status: [Alpha]
type ExportProfilesServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An array of ResourceProfiles.
	// For data coming from a single resource this array will typically contain one
	// element. Intermediary nodes (such as OpenTelemetry Collector) that receive
	// data from multiple origins typically batch the data before forwarding further and
	// in that case this array will contain multiple elements.
	ResourceProfiles []*v1development.ResourceProfiles `protobuf:"bytes,1,rep,name=resource_profiles,json=resourceProfiles,proto3" json:"resource_profiles,omitempty"`
	// The reference table containing all data shared by profiles across the message being sent.
	Dictionary    *v1development.ProfilesDictionary `protobuf:"bytes,2,opt,name=dictionary,proto3" json:"dictionary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportProfilesServiceRequest) Reset() {
	*x = ExportProfilesServiceRequest{}
	mi := &file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportProfilesServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportProfilesServiceRequest) ProtoMessage() {}

func (x *ExportProfilesServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportProfilesServiceRequest.ProtoReflect.Descriptor instead.
func (*ExportProfilesServiceRequest) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDescGZIP(), []int{0}
}

func (x *ExportProfilesServiceRequest) GetResourceProfiles() []*v1development.ResourceProfiles {
	if x != nil {
		return x.ResourceProfiles
	}
	return nil
}

func (x *ExportProfilesServiceRequest) GetDictionary() *v1development.ProfilesDictionary {
	if x != nil {
		return x.Dictionary
	}
	return nil
}

// Status: [Alpha]
type ExportProfilesServiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The details of a partially successful export request.
	//
	// If the request is only partially accepted
	// (i.e. when the server accepts only parts of the data and rejects the rest)
	// the server MUST initialize the `partial_success` field and MUST
	// set the `rejected_<signal>` with the number of items it rejected.
	//
	// Servers MAY also make use of the `partial_success` field to convey
	// warnings/suggestions to senders even when the request was fully accepted.
	// In such cases, the `rejected_<signal>` MUST have a value of `0` and
	// the `error_message` MUST be non-empty.
	//
	// A `partial_success` message with an empty value (rejected_<signal> = 0 and
	// `error_message` = "") is equivalent to it not being set/present. Senders
	// SHOULD interpret it the same way as in the full success case.
	PartialSuccess *ExportProfilesPartialSuccess `protobuf:"bytes,1,opt,name=partial_success,json=partialSuccess,proto3" json:"partial_success,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExportProfilesServiceResponse) Reset() {
	*x = ExportProfilesServiceResponse{}
	mi := &file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportProfilesServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportProfilesServiceResponse) ProtoMessage() {}

func (x *ExportProfilesServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportProfilesServiceResponse.ProtoReflect.Descriptor instead.
func (*ExportProfilesServiceResponse) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDescGZIP(), []int{1}
}

func (x *ExportProfilesServiceResponse) GetPartialSuccess() *ExportProfilesPartialSuccess {
	if x != nil {
		return x.PartialSuccess
	}
	return nil
}

// Status: [Alpha]
type ExportProfilesPartialSuccess struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of rejected profiles.
	//
	// A `rejected_<signal>` field holding a `0` value indicates that the
	// request was fully accepted.
	RejectedProfiles int64 `protobuf:"varint,1,opt,name=rejected_profiles,json=rejectedProfiles,proto3" json:"rejected_profiles,omitempty"`
	// A developer-facing human-readable message in English. It should be used
	// either to explain why the server rejected parts of the data during a partial
	// success or to convey warnings/suggestions during a full success. The message
	// should offer guidance on how users can address such issues.
	//
	// error_message is an optional field. An error_message with an empty value
	// is equivalent to it not being set.
	ErrorMessage  string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportProfilesPartialSuccess) Reset() {
	*x = ExportProfilesPartialSuccess{}
	mi := &file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportProfilesPartialSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportProfilesPartialSuccess) ProtoMessage() {}

func (x *ExportProfilesPartialSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportProfilesPartialSuccess.ProtoReflect.Descriptor instead.
func (*ExportProfilesPartialSuccess) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDescGZIP(), []int{2}
}

func (x *ExportProfilesPartialSuccess) GetRejectedProfiles() int64 {
	if x != nil {
		return x.RejectedProfiles
	}
	return 0
}

func (x *ExportProfilesPartialSuccess) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto protoreflect.FileDescriptor

const file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDesc = "" +
	"\n" +
	"Kopentelemetry/proto/collector/profiles/v1development/profiles_service.proto\x124opentelemetry.proto.collector.profiles.v1development\x1a9opentelemetry/proto/profiles/v1development/profiles.proto\"\xe9\x01\n" +
	"\x1cExportProfilesServiceRequest\x12i\n" +
	"\x11resource_profiles\x18\x01 \x03(\v2<.opentelemetry.proto.profiles.v1development.ResourceProfilesR\x10resourceProfiles\x12^\n" +
	"\n" +
	"dictionary\x18\x02 \x01(\v2>.opentelemetry.proto.profiles.v1development.ProfilesDictionaryR\n" +
	"dictionary\"\x9c\x01\n" +
	"\x1dExportProfilesServiceResponse\x12{\n" +
	"\x0fpartial_success\x18\x01 \x01(\v2R.opentelemetry.proto.collector.profiles.v1development.ExportProfilesPartialSuccessR\x0epartialSuccess\"p\n" +
	"\x1cExportProfilesPartialSuccess\x12+\n" +
	"\x11rejected_profiles\x18\x01 \x01(\x03R\x10rejectedProfiles\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xc7\x01\n" +
	"\x0fProfilesService\x12\xb3\x01\n" +
	"\x06Export\x12R.opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest\x1aS.opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceResponse\"\x00B\xce\x01\n" +
	"7io.opentelemetry.proto.collector.profiles.v1developmentB\x14ProfilesServiceProtoP\x01ZDgo.opentelemetry.io/proto/slim/otlp/collector/profiles/v1development\xaa\x024OpenTelemetry.Proto.Collector.Profiles.V1Developmentb\x06proto3"

var (
	file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDescOnce sync.Once
	file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDescData []byte
)

func file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDescGZIP() []byte {
	file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDescOnce.Do(func() {
		file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDesc), len(file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDesc)))
	})
	return file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDescData
}

var file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_goTypes = []any{
	(*ExportProfilesServiceRequest)(nil),     // 0: opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest
	(*ExportProfilesServiceResponse)(nil),    // 1: opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceResponse
	(*ExportProfilesPartialSuccess)(nil),     // 2: opentelemetry.proto.collector.profiles.v1development.ExportProfilesPartialSuccess
	(*v1development.ResourceProfiles)(nil),   // 3: opentelemetry.proto.profiles.v1development.ResourceProfiles
	(*v1development.ProfilesDictionary)(nil), // 4: opentelemetry.proto.profiles.v1development.ProfilesDictionary
}
var file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_depIdxs = []int32{
	3, // 0: opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest.resource_profiles:type_name -> opentelemetry.proto.profiles.v1development.ResourceProfiles
	4, // 1: opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest.dictionary:type_name -> opentelemetry.proto.profiles.v1development.ProfilesDictionary
	2, // 2: opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceResponse.partial_success:type_name -> opentelemetry.proto.collector.profiles.v1development.ExportProfilesPartialSuccess
	0, // 3: opentelemetry.proto.collector.profiles.v1development.ProfilesService.Export:input_type -> opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest
	1, // 4: opentelemetry.proto.collector.profiles.v1development.ProfilesService.Export:output_type -> opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_init() }
func file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_init() {
	if File_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDesc), len(file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_goTypes,
		DependencyIndexes: file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_depIdxs,
		MessageInfos:      file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_msgTypes,
	}.Build()
	File_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto = out.File
	file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_goTypes = nil
	file_opentelemetry_proto_collector_profiles_v1development_profiles_service_proto_depIdxs = nil
}
