// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: opentelemetry/proto/processcontext/v1development/process_context.proto

package v1development

import (
	v11 "go.opentelemetry.io/proto/otlp/common/v1"
	v1 "go.opentelemetry.io/proto/otlp/resource/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProcessContext represents the payload for the process context sharing mechanism.
//
// This message is designed to be published by OpenTelemetry SDKs via a memory-mapped
// region, allowing external readers (such as the OpenTelemetry eBPF Profiler) to
// discover and read resource attributes from instrumented processes without requiring
// direct integration or process activity. It is not part of OTLP and is not
// exchanged via the OpenTelemetry Collector.
//
// See OTEP 4719 (https://github.com/open-telemetry/opentelemetry-specification/blob/main/oteps/profiles/4719-process-ctx.md)
// for details of this mechanism.
//
// Status: [Development]
type ProcessContext struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The resource for this process.
	// If this field is not set then no resource info is known.
	Resource *v1.Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Additional attributes to share with external readers that are not part of
	// the standard Resource. [Optional]
	//
	// This field allows publishers to include supplementary key-value pairs that
	// may be useful for external readers but are not part of the SDK's configured
	// Resource.
	//
	// Consider adding any keys here to the profiles semantic conventions in
	// https://opentelemetry.io/docs/specs/semconv/general/profiles/
	Attributes    []*v11.KeyValue `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessContext) Reset() {
	*x = ProcessContext{}
	mi := &file_opentelemetry_proto_processcontext_v1development_process_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessContext) ProtoMessage() {}

func (x *ProcessContext) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_processcontext_v1development_process_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessContext.ProtoReflect.Descriptor instead.
func (*ProcessContext) Descriptor() ([]byte, []int) {
	return file_opentelemetry_proto_processcontext_v1development_process_context_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessContext) GetResource() *v1.Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ProcessContext) GetAttributes() []*v11.KeyValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_opentelemetry_proto_processcontext_v1development_process_context_proto protoreflect.FileDescriptor

const file_opentelemetry_proto_processcontext_v1development_process_context_proto_rawDesc = "" +
	"\n" +
	"Fopentelemetry/proto/processcontext/v1development/process_context.proto\x120opentelemetry.proto.processcontext.v1development\x1a*opentelemetry/proto/common/v1/common.proto\x1a.opentelemetry/proto/resource/v1/resource.proto\"\xa0\x01\n" +
	"\x0eProcessContext\x12E\n" +
	"\bresource\x18\x01 \x01(\v2).opentelemetry.proto.resource.v1.ResourceR\bresource\x12G\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2'.opentelemetry.proto.common.v1.KeyValueR\n" +
	"attributesB\xbc\x01\n" +
	"3io.opentelemetry.proto.processcontext.v1developmentB\x13ProcessContextProtoP\x01Z;go.opentelemetry.io/proto/otlp/processcontext/v1development\xaa\x020OpenTelemetry.Proto.ProcessContext.V1Developmentb\x06proto3"

var (
	file_opentelemetry_proto_processcontext_v1development_process_context_proto_rawDescOnce sync.Once
	file_opentelemetry_proto_processcontext_v1development_process_context_proto_rawDescData []byte
)

func file_opentelemetry_proto_processcontext_v1development_process_context_proto_rawDescGZIP() []byte {
	file_opentelemetry_proto_processcontext_v1development_process_context_proto_rawDescOnce.Do(func() {
		file_opentelemetry_proto_processcontext_v1development_process_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opentelemetry_proto_processcontext_v1development_process_context_proto_rawDesc), len(file_opentelemetry_proto_processcontext_v1development_process_context_proto_rawDesc)))
	})
	return file_opentelemetry_proto_processcontext_v1development_process_context_proto_rawDescData
}

var file_opentelemetry_proto_processcontext_v1development_process_context_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_opentelemetry_proto_processcontext_v1development_process_context_proto_goTypes = []any{
	(*ProcessContext)(nil), // 0: opentelemetry.proto.processcontext.v1development.ProcessContext
	(*v1.Resource)(nil),    // 1: opentelemetry.proto.resource.v1.Resource
	(*v11.KeyValue)(nil),   // 2: opentelemetry.proto.common.v1.KeyValue
}
var file_opentelemetry_proto_processcontext_v1development_process_context_proto_depIdxs = []int32{
	1, // 0: opentelemetry.proto.processcontext.v1development.ProcessContext.resource:type_name -> opentelemetry.proto.resource.v1.Resource
	2, // 1: opentelemetry.proto.processcontext.v1development.ProcessContext.attributes:type_name -> opentelemetry.proto.common.v1.KeyValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_opentelemetry_proto_processcontext_v1development_process_context_proto_init() }
func file_opentelemetry_proto_processcontext_v1development_process_context_proto_init() {
	if File_opentelemetry_proto_processcontext_v1development_process_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opentelemetry_proto_processcontext_v1development_process_context_proto_rawDesc), len(file_opentelemetry_proto_processcontext_v1development_process_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opentelemetry_proto_processcontext_v1development_process_context_proto_goTypes,
		DependencyIndexes: file_opentelemetry_proto_processcontext_v1development_process_context_proto_depIdxs,
		MessageInfos:      file_opentelemetry_proto_processcontext_v1development_process_context_proto_msgTypes,
	}.Build()
	File_opentelemetry_proto_processcontext_v1development_process_context_proto = out.File
	file_opentelemetry_proto_processcontext_v1development_process_context_proto_goTypes = nil
	file_opentelemetry_proto_processcontext_v1development_process_context_proto_depIdxs = nil
}
