// Code generated by protoc-gen-goshim. DO NOT EDIT.

package v1

import slim "go.opentelemetry.io/proto/slim/otlp/metrics/v1"

type (
	MetricsData                   = slim.MetricsData
	ResourceMetrics               = slim.ResourceMetrics
	ScopeMetrics                  = slim.ScopeMetrics
	Metric                        = slim.Metric
	Gauge                         = slim.Gauge
	Sum                           = slim.Sum
	Histogram                     = slim.Histogram
	ExponentialHistogram          = slim.ExponentialHistogram
	Summary                       = slim.Summary
	NumberDataPoint               = slim.NumberDataPoint
	HistogramDataPoint            = slim.HistogramDataPoint
	ExponentialHistogramDataPoint = slim.ExponentialHistogramDataPoint
	SummaryDataPoint              = slim.SummaryDataPoint
	Exemplar                      = slim.Exemplar
	AggregationTemporality        = slim.AggregationTemporality
	DataPointFlags                = slim.DataPointFlags
)
