// Code generated by protoc-gen-goshim. DO NOT EDIT.

package v1

import slim "go.opentelemetry.io/proto/slim/otlp/collector/logs/v1"

type (
	ExportLogsServiceRequest  = slim.ExportLogsServiceRequest
	ExportLogsServiceResponse = slim.ExportLogsServiceResponse
	ExportLogsPartialSuccess  = slim.ExportLogsPartialSuccess
)
