// Code generated by protoc-gen-goshim. DO NOT EDIT.

package v1

import slim "go.opentelemetry.io/proto/slim/otlp/collector/metrics/v1"

type ExportMetricsServiceRequest = slim.ExportMetricsServiceRequest
type ExportMetricsServiceResponse = slim.ExportMetricsServiceResponse
type ExportMetricsPartialSuccess = slim.ExportMetricsPartialSuccess
