// Code generated by protoc-gen-goshim. DO NOT EDIT.

package v1

import slim "go.opentelemetry.io/proto/slim/otlp/collector/trace/v1"

type (
	ExportTraceServiceRequest  = slim.ExportTraceServiceRequest
	ExportTraceServiceResponse = slim.ExportTraceServiceResponse
	ExportTracePartialSuccess  = slim.ExportTracePartialSuccess
)
