// Code generated by protoc-gen-goshim. DO NOT EDIT.

package v1

import slim "go.opentelemetry.io/proto/slim/otlp/logs/v1"

type (
	LogsData       = slim.LogsData
	ResourceLogs   = slim.ResourceLogs
	ScopeLogs      = slim.ScopeLogs
	LogRecord      = slim.LogRecord
	SeverityNumber = slim.SeverityNumber
	LogRecordFlags = slim.LogRecordFlags
)
