// Code generated by protoc-gen-goshim. DO NOT EDIT.

package v1development

import slim "go.opentelemetry.io/proto/slim/otlp/collector/profiles/v1development"

type ExportProfilesServiceRequest = slim.ExportProfilesServiceRequest
type ExportProfilesServiceResponse = slim.ExportProfilesServiceResponse
type ExportProfilesPartialSuccess = slim.ExportProfilesPartialSuccess
