name: Dependabot Coverage
on:
  pull_request:
jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Run check
      run: make dependabot-check
