name: Check modules
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.21.12"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Generate
        run: make crosslink go-mod-tidy
      - name: Check Clean Work Tree
        run: make check-clean-work-tree
